### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by ManuelSchneid3r**

### CODE REVIEW

**Comment by NicoWeio** [comment]
Thanks! I'll merge this once I can test it, which will be in another month or so.

**Comment by ManuelSchneid3r** [comment]
It is a one liner once docker is installed. Nothing to save a date for imho

**Comment by ManuelSchneid3r** [comment]
Nico? are you still intersted in merging this one?

**Comment by NicoWeio** [comment]
Well, that took a while – thanks for your patience! 
As you can see, I've modified your Dockerfile a bit, which I _think_ improves build caching.

**Pull request merged**
